[project]
name = "cdm-spark-standalone"
version = "0.1.0"
description = "CDM Spark Standalone"
readme = "README.md"
requires-python = "==3.12.10"
dependencies = [
    "pyspark==4.0.0",
]

[dependency-groups]
dev = [
    "ipython>=9.2.0",
    "pytest==8.3.5",
    "pytest-cov==6.1.1",
]
